### ISSUE TITLE
BUG: Check out button

### ISSUE THREAD

**Issue by mewing0328** [leeclaire156/Produce-Pal#101]
@lzh1990214 
When logged out, add styling to the "Login or Signup Button" where "Checkout" would be if the user is logged in

**Comment by lzh1990214** [comment]
The problem is: do we want to disable the 'add to cart' button if the user is not logged in. It's complicated to do another persistent globalState of cart. Otherwise the cart will be gone if the user click login button.

**Comment by leeclaire156** [comment]
resolved: I added a render button to the product cards that say "Log in to add" that appears in place of the "Add to cart" buttons. 

When users are logged in, this button is replaced with "Add to cart".
