### ISSUE TITLE
HIGH PRIORITY: Required feature: product decrement

### ISSUE THREAD

**Issue by mewing0328** [leeclaire156/Produce-Pal#114]
After an order is made, reduce the product objectID's productInventory number by how many items of that product was purchased 
- Note: backend mutation function in resolvers and works
- To Do: implement the mutation on the front end

**Comment by leeclaire156** [comment]
If this feature cannot be implemented, then take out inventory counts across the board (create product forms, edit product forms, cards, etc) and make sure product availability: No will hide the products. That will be our soft delete.

If this can be implemented, make sure inventory: 0 will hide the products and/or set product availability to _No_.

**Comment by leeclaire156** [comment]
Went with option 1
