### ISSUE TITLE
Make route /profile/consumer/:id functional

### ISSUE THREAD

**Issue by lzh1990214** [leeclaire156/Produce-Pal#121]
{/* this route is for farmer to view their consumers who bought their products */}
              <Route exact path='/profile/consumer/:id' component={ProfileOtherConsumer} />

**Comment by leeclaire156** [comment]
To everyone but Zhihao (cause he already knows this), route `/profile/consumer/:id` is functional, but unlinked. 


So you can render if you enter in URL but currently not accessible by clicking on anything on webpage.

**Comment by mewing0328** [comment]
Working on this one.
Link doesn't like the props so trying something else

**Comment by mewing0328** [comment]
@lzh1990214 will try to take a look at the props. I tried creating the link mirroring what you did with farmcard but it wasn't working for me. 

I will try another approach outside of props - stay tuned

**Comment by mewing0328** [comment]
Resolved with PR #161 and #163
