### ISSUE TITLE
Disable private Routes (dashboard and my profile)if a User is not Logged In and Redirect user to log in

### ISSUE THREAD

**Issue by lzh1990214** [leeclaire156/Produce-Pal#122]
Disable private Routes (dashboard and my profile)if a User is not Logged In and Redirect user to log in

**Comment by leeclaire156** [comment]
routes locked to user when not logged in and redirected to login:

- `/dashboard`
- `/profile`
- `/order-history`
- `/productInventory`
- `/profile/consumer/:id` (currently not linked anywhere but does render, please remind Zhihao of his plans to link this on vendor's sale history page. unless his plans for that changed then nvm. See `issue #121`)
- `/profile/vendor/:id`

- `/productInventoryother/:id` (other storepages) is available for viewing when logged out but users cannot purchase unless logged in

- `/success` currently unlocked, will be locked (making a PR in 10 minutes)

routes open to users when not logged in:
- `/` homepage
- `/login`
- `/signup`

**Comment by leeclaire156** [comment]
PR made for success page lock.
