### ISSUE TITLE
[COMPLETE(?) - see comments] Seeds.js

### ISSUE THREAD

**Issue by mewing0328** [leeclaire156/Produce-Pal#71]
Full ownership passed to Quin 
- data added
- functions working properly
- full seeds with substantial information

**Comment by leeclaire156** [comment]
currently hyperlinks are being fixed by @JMess87

**Comment by leeclaire156** [comment]
seeds were fixed by @JMess87  and @mewing0328

**Comment by leeclaire156** [comment]
This can be closed (and reopened if needed) but just letting you know that the `orderId` generator is a 12-character string of numbers. The current seeds' `orderId` are 4 characters long; HOWEVER, since we can't log into the accounts, we will never see this orders :'(.

**Comment by mewing0328** [comment]
Yeah, we never will :( they are lost children of the seeded file. Ha!

Go ahead and close.  If we need to reopen, we can.
