### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by leeclaire156** [leeclaire156/Produce-Pal#73]
Would've like validations for...

Sign up page:
first name required
last name required
email required
password required (and must be at least 5 characters)
are you a vendor? status required

Login page:
email input
password input
incorrect email or password

**Comment by leeclaire156** [comment]
With the rate we're going at the very least, @JMess87 needs to make "Incorrect email or password" text to appear on login by end of today (4/30/23), already left a message to her slack at around 3 am. [Same as issue #99 ]

**Comment by JMess87** [comment]
Validation on sign up page (required bubble when left blank) first name, last name, email , password (Done)
Validation show as required username and password in login in screen (Done)

Incorrect email and password pop error is in the code but the syntax is wonky. It is there and doesn't break anything but isn't rending showing the error.

**Comment by leeclaire156** [comment]
@JMess87 resolved it :)
