### ISSUE TITLE
BUG: Shopping Cart

### ISSUE THREAD

**Issue by mewing0328** [leeclaire156/Produce-Pal#86]
Order by priority
1. Changing the quantity in the cart doesn't change the totals and subtotals for cost
2. Can't add multiples of the same item; need to update inside the cart

**Comment by leeclaire156** [comment]
issue: clicking on the same item causes the quantity to go up in code (and stripe) and updates the total, but visually the quantity input remains at one.

**Comment by leeclaire156** [comment]
issue 1 resolved, issue 2 still yet to be resolved.

**Comment by leeclaire156** [comment]
issue 2 slightly resolved, see PR #154

**Comment by leeclaire156** [comment]
resolved with PR #179
